version: "3.9"
services:
  app:
    image: nishthamavai/todo-app:latest
    ports:
      - 5001:5000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todo_db
